web/blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    # .../blog/
    path('', PostLV.as_view(), name='index'),
    # .../blog/post/
    path('post/', PostLV.as_view(), name='post_list'),
    # .../blog/post/slug
    path('post/<str:slug>/', PostDV.as_view(), name='post_detail'),
    # .../blog/archive/
    path('archive/', PostAV.as_view(), name='post_archive'),
    path('<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),
    path('<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),
    path('today/', PostTAV.as_view(), name='post_today_archive'),
    path('tag/', TagTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', PostOV.as_view(), name='tagged_object_list'),
    # .../blog/search/
    path('search/', SearchFormView.as_view(), name='search'),

    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeLV.as_view(), name='change'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete')
]

web/bookmark/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'bookmark'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', BookmarkLV.as_view(model=Bookmark), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(model=Bookmark), name='detail'),
    path('add/', BookmarkCreateView.as_view(model=Bookmark), name='add'),
    path('change/', BookmarkChangeLV.as_view(model=Bookmark), name='change'),
    path('<int:pk>/update/', BookmarkUpdateView.as_view(model=Bookmark), name='update'),
    path('<int:pk>/delete/', BookmarkDeleteView.as_view(model=Bookmark), name='delete'),
]

web/photo/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'photo'

urlpatterns = [
    path('', AlbumLV.as_view(), name='index'),
    path('album/', AlbumLV.as_view(), name='album_list'),
    path('album/<int:pk>/', AlbumDV.as_view(), name='album_detail'),
    path('photo/<int:pk>/', PhotoDV.as_view(), name='photo_detail'),

    path('album/add/', AlbumPhotoCV.as_view(), name='album_add'),
    path('album/change/', AlbumChangeLV.as_view(), name='album_change'),
    path('album/<int:pk>/update/', AlbumPhotoUV.as_view(), name='album_update'),
    path('album/<int:pk>/delete/', AlbumDeleteView.as_view(), name='album_delete'),
    path('photo/add/', PhotoCreateView.as_view(), name='photo_add'),
    path('photo/change/', PhotoChangeLV.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/', PhotoUpdateView.as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name='photo_delete'),
]

web/web/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from .views import HomeView  # 홈 뷰
from .views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),  # 홈 뷰 추가
    path('bookmark/', include('bookmark.urls',), name='bookmark'),
    path('blog/', include('blog.urls',), name='blog'),
    path('photo/', include('photo.urls',), name='photo'),
    path('polls/', include('polls.urls',), name='polls'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

web/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}Django Web Programming{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% load staticfiles %}
<!--    <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static 'css/base.css' %}{% endblock %}">-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

</head>
<body>

    <div id="header">
        <h2 class="maintitle">Easy&amp;Fast Django Web Programming</h2>
        {% if user.is_active %}
        <h4 class="welcome">Welcome,
            <strong>{% firstof user.get_short_name user.get_username %}</strong>
            <a href="{% url 'password_change' %}">Change Password</a> /
            <a href="{% url 'logout' %}">Logout</a>
        </h4>
        {% else %}
        <h4 class="welcome">
            <a href="{% url 'login' %}">Login</a> /
            <a href="{% url 'register' %}">Register</a>
        </h4>
        {% endif %}
    </div>

    <div id="menu">
        <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'bookmark:index' %}">Bookmark</a></li>
            <li><a href="{% url 'blog:index' %}">Blog</a></li>
            <li><a href="{% url 'photo:index' %}">Photo</a></li>
            <li><a href="#">Add +</a>
                <ul>
                    <li><a href="{% url 'bookmark:add' %}">Bookmark</a></li>
                    <li><a href="{% url 'blog:add' %}">Blog</a></li>
                    <li><a href="{% url 'photo:album_add' %}">Album</a></li>
                    <li><a href="{% url 'photo:photo_add' %}">Photo</a></li>
                </ul>
            </li>
            <li><a href="#">Modify +</a>
                <ul>
                    <li><a href="{% url 'bookmark:change' %}">Bookmark</a></li>
                    <li><a href="{% url 'blog:change' %}">Blog</a></li>
                    <li><a href="{% url 'photo:album_change' %}">Album</a></li>
                    <li><a href="{% url 'photo:photo_change' %}">Photo</a></li>
                </ul>
            </li>
            <li><a href="{% url 'blog:post_archive' %}">Archive</a></li>
            <li><a href="{% url 'blog:search' %}">Search</a></li>
            <li><a href="{% url 'admin:index' %}">Admin</a></li>
        </ul>
    </div>

    {% block content %}{% endblock %}
    {% block footer %}{% endblock %}


    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

web/templates/home.html
{% extends "base.html" %}
{% block title %}home.html{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static 'css/home.css' %}{% endblock %}

{% block content %}
<div id="content">
    <div id="content_home">
        <div id="homeimg">
            <a href="/"><img src="{% static 'img/django-actor-big.jpg' %}" style="height:256px;"></a>
            <h4 style="margin:0">장고는 강력한 웹 사이트 지원 프레임워크이다.</h4>
        </div>

        <hr style="margin:5px 0">
        <h3>애플리케이션 선택</h3>
        <table id="applist" class="table table-bordered">
            <tr>
                <td><b><i><a href="{% url 'bookmark:index' %}">Bookmark</a></i></b></td>
                <td>다른 사람들을 위해 자신의 북마크 작성 가능.</td>
                <td class="Edit"><i><a href="{% url 'bookmark:add' %}">Add</a></i></td>
                <td class="Edit"><i><a href="{% url 'bookmark:change' %}">Change</a></i></td>
            </tr>
            <tr>
                <td><b><i><a href="{% url 'blog:index' %}">Blog</a></i></b></td>
                <td>다른 사람들을 위해 자신의 블로그 작성 가능.</td>
                <td class="Edit"><i><a href="{% url 'blog:add' %}">Add</a></i></td>
                <td class="Edit"><i><a href="{% url 'blog:change' %}">Change</a></i></td>
            </tr>
            <tr>
                <td><b><i><a href="{% url 'photo:index' %}">Photo</a></i></b></td>
                <td>다른 사람들을 위해 자신의 사진 올리기 가능.</td>
                <td class="Edit"><i><a href="{% url 'photo:album_add' %}">Add</a></i></td>
                <td class="Edit"><i><a href="{% url 'photo:album_change' %}">Change</a></i></td>
            </tr>

        </table>
    </div>
</div>
{% endblock content %}

{% block footer %}
    <div id="footer">&copy; Django for Python 2019.</div>
{% endblock %}