web/bookmark/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'bookmark'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', BookmarkLV.as_view(model=Bookmark), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(model=Bookmark), name='detail'),
    path('add/', BookmarkCreateView.as_view(model=Bookmark), name='add'),
    path('change/', BookmarkChangeLV.as_view(model=Bookmark), name='change'),
    path('<int:pk>/update/', BookmarkUpdateView.as_view(model=Bookmark), name='update'),
    path('<int:pk>/delete/', BookmarkDeleteView.as_view(model=Bookmark), name='delete'),
]

web/web/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from .views import HomeView  # 홈 뷰
from .views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),  # 홈 뷰 추가
    path('bookmark/', include('bookmark.urls',), name='bookmark'),
    path('blog/', include('blog.urls',), name='blog'),
    path('photo/', include('photo.urls',), name='photo'),
    path('polls/', include('polls.urls',), name='polls'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

web/bookmark/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User
# 1,3번 설정으로 python2 환경에서도 보이게 함.


@python_2_unicode_compatible
class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    # 필드명=models.데이터타입(제약조건=값, ...)
    url = models.URLField('url', unique=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE,)

    def __str__(self):  # __str__ 메서드는 객체명만 사용할때 주소 리턶는 것을 특정 문자열로 반환.
        return self.title

web/bookmark/views.py
from django.shortcuts import render
# generic 의 기존 view를 상속받음
from django.views.generic import ListView, DetailView
from .models import Bookmark
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from web.views import LoginRequiredMixin


class BookmarkLV(ListView):
    model = Bookmark


class BookmarkDV(DetailView):
    model = Bookmark


class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(BookmarkCreateView, self).form_valid(form)


class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)


class BookmarkUpdateView(LoginRequiredMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')


class BookmarkDeleteView(LoginRequiredMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

web/bookmark/templates/bookmark/bookmark_change_list.html
{% extends "base.html" %}
{% block title %}Bookmark Change List{% endblock %}
{% block content %}
    <div id="content">
        <h1>Boookmark Change - {{ user }}</h1>

        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>Title</th>
                    <th>URL</th>
                    <th>Owner</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for item in object_list %}
                <tr>
                    <td>{{ item.title }}</td>
                    <td>{{ item.url }}</td>
                    <td>{{ item.owner }}</td>
                    <td><a href="{% url 'bookmark:update' item.id %}">Update</a></td>
                    <td><a href="{% url 'bookmark:delete' item.id %}">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
{% endblock content %}

{% block footer %}
    <div id="footer">&copy; Django for Python 2019.</div>
{% endblock %}

web/bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends "base.html" %}
{% block title %}Bookmark Confirm Delete{% endblock %}
{% block content %}
    <div id="content">
        <h1>Bookmark Delete</h1>

        <form action="." method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"</p>
            <input type="submit" class="btn btn-primary" value="Confirm">
        </form>
    </div>
{% endblock content %}

{% block footer %}
    <div id="footer">&copy; Django for Python 2019.</div>
{% endblock %}

web/bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}
{% block title %}Django Bookmark Detail{% endblock %}
{% block content %}
    <div id="conent">
        <h1>{{ object.title }}</h1>
        <hr>
        <ul>
            <li>URL: <a href="{{ object.url }}" target="_blank">{{ object.title }}: {{ object.url }}</a></li>
        </ul>

    </div>
{% endblock content %}

{% block footer %}
    <div id="footer">&copy; Django for Python 2019.</div>
{% endblock %}

web/bookmark/templates/bookmark/bookmark_form.html
{% extends "base.html" %}
{% block title %}Bookmark Form{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static 'css/form.css' %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Boookmark Create/Update - {{ user }}</h1>

        <form action="." method="post">{% csrf_token %}

            {% if form.errors %}
            <p class="errornote">Wrong! Please correct the errors below.</p>
            {% endif %}

            <p>This is a creation or update form for your bookmark.</p>

            <fieldset class="aligned">
                <div class="form-group">
                    {{ form.title.label_tag }} {{ form.title }}
                </div>
                <div class="form-group">
                    {{ form.url.label_tag }} {{ form.url }}
                </div>
            </fieldset>

            <div class="submit-row">
                <input type="submit" class="btn btn-primary" value="Submit">
            </div>

            <script type="text/javascript">
                document.getElementById('id_title').focus();
            </script>
        </form>
    </div>
{% endblock content %}

{% block footer %}
    <div id="footer">&copy; Django for Python 2019.</div>
{% endblock %}

web/bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}
{% block title %}Django Bookmark List{% endblock %}
{% block content %}
    <div id="content">
        <h1>Boookmark List</h1>
        <ul>
            {% for bookmark in object_list %}
                <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

{% block footer %}
    <div id="footer">&copy; Django for Python 2019.</div>
{% endblock %}