web/blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    # .../blog/
    path('', PostLV.as_view(), name='index'),
    # .../blog/post/
    path('post/', PostLV.as_view(), name='post_list'),
    # .../blog/post/slug
    path('post/<str:slug>/', PostDV.as_view(), name='post_detail'),
    # .../blog/archive/
    path('archive/', PostAV.as_view(), name='post_archive'),
    path('<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),
    path('<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),
    path('today/', PostTAV.as_view(), name='post_today_archive'),
    path('tag/', TagTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', PostOV.as_view(), name='tagged_object_list'),
    # .../blog/search/
    path('search/', SearchFormView.as_view(), name='search'),

    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeLV.as_view(), name='change'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete')
]

web/web/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from .views import HomeView  # 홈 뷰
from .views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),  # 홈 뷰 추가
    path('bookmark/', include('bookmark.urls',), name='bookmark'),
    path('blog/', include('blog.urls',), name='blog'),
    path('photo/', include('photo.urls',), name='photo'),
    path('polls/', include('polls.urls',), name='polls'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

web/blog/models.py
from __future__ import unicode_literals
from django.db import models
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible
from tagging.fields import TagField
# 1,3번 설정으로 python2 환경에서도 보이게 함.
from django.contrib.auth.models import User
from django.utils.text import slugify


@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='제목을 위한 별칭으로 한개의 단어로 사용')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True)
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_date = models.DateTimeField('MODIFY DATE', auto_now=True)
    tag = TagField()
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE,)

    class Meta:
        verbose_name = 'post'  # 이 이름을 이용해서 표시 가능
        verbose_name_plural = 'posts'
        db_table = 'my_post'
        ordering = ('-modify_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))
        # return reverse('blog:post_detail', kwargs={'slug': self.slug})

    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title, allow_unicode=True)
        super(Post, self).save(*args, **kwargs)

web/blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label="Search Word")

web/blog/views.py
from django.views.generic import ListView, DetailView, TemplateView, FormView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView

from .models import Post
from tagging.models import Tag, TaggedItem
from tagging.views import TaggedObjectList

from .forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from web.views import LoginRequiredMixin


class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'  # 템플릿 이름을 수동으로 설정
    paginate_by = 2  # 한페이지에 2줄
    context_object_name = 'posts'  # 메타에서 사용. tamplates 에서 이름 사용 / object list 대신 사용 가능


class PostDV(DetailView):
    model = Post


class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True


class PostMAV(MonthArchiveView):
    model = Post
    month_format = '%m'  # 추가
    date_field = 'modify_date'


class PostDAV(DayArchiveView):
    model = Post
    month_format = '%m'
    day_format = '%d'
    date_field = 'modify_date'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'


class TagTV(TemplateView):
    template_name = 'tagging/tagging_cloud.html'


class PostOV(TaggedObjectList):
    model = Post
    template_name = 'tagging/tagging_post_list.html'


class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = "blog/post_search.html"

    def form_valid(self, form):
        schWord = "%s" % self.request.POST['search_word']
        post_list = Post.objects.filter(Q(title__icontains=schWord) |
                                        Q(description__icontains=schWord) |
                                        Q(content__icontains=schWord)).distinct()
        context = {}
        context['form'] = form
        context['search_term'] = schWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)  # No redirection


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tag']
    initial = {'slug': 'auto-filling-do-not-input'}
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PostCreateView, self).form_valid(form)


class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tag']
    success_url = reverse_lazy('blog:index')


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

web/blog/templates/blog/post_all.html
{% extends "base.html" %}
{% block title %}Blog List{% endblock %}
{% block content %}
    <div id="content">
        <h1>Blog List</h1>
        <hr>
        {% for post in posts %}
            <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a> </h2>
            {{ post.modify_date|date:"N d, Y" }}
            <p>{{ post.description }}</p>
        {% endfor %}

        <br>
        <div>
            <span>
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">
                        PreviousPage
                    </a>
                {% endif %}
                Page{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">
                        NextPage
                    </a>
                {% endif %}
            </span>
        </div>
    </div>
{% endblock content %}

{% block footer %}
    <div id="footer">&copy; Django for Python 2019.</div>
{% endblock %}

web/blog/templates/blog/post_archive.html
{% extends "base.html" %}
{% block title %}Post Archive{% endblock %}
{% block content %}
    <div id="content">
        <h1>Post Archive until {% now "N d, Y" %}</h1>
        <ul>
            {% for date in date_list %}
                <li style="display:inline-block; margin-right:1em">
                    <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">
                        Year={{ date|date:'Y' }}
                    </a>
                </li>
            {% endfor %}
        </ul>
        <br>
        <div>
            <ul>
                {% for post in object_list %}
                    <li>
                        {{ post.modify_date|date:'Y-m-d' }} &nbsp;
                        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}

{% block footer %}
    <div id="footer">&copy; Django for Python 2019.</div>
{% endblock %}

web/blog/templates/blog/post_archive_day.html
{% extends "base.html" %}
{% block title %}Post Archive{% endblock %}
{% block content %}
    <div id="content">
        <h1>Post Archive for {{ day|date:"N d, Y" }}</h1>

        <div>
            <ul>
                {% for post in object_list %}
                    <li>
                        {{ post.modify_date|date:'Y-m-d' }}&nbsp;
                        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                    </li>
                {% endfor %}
            </ul>
        </div>

    </div>
{% endblock content %}

{% block footer %}
    <div id="footer">&copy; Django for Python 2019.</div>
{% endblock %}

web/blog/templates/blog/post_archive_month.html
{% extends "base.html" %}
{% block title %}Post Archive{% endblock %}
{% block content %}
    <div id="content">
        <h1>Post Archive for {{ month|date:"N, Y" }}</h1>

        <ul>
            {% for date in date_list %}
                <li style="display:inline-block; margin-right:1em">
                    <a href="{% url 'blog:post_day_archive' date|date:'Y' date|date:'m' date|date:'d' %}">
                        {{ date|date:'m-d' }}
                    </a>
                </li>
            {% endfor %}
        </ul>

        <div>
            <ul>
                {% for post in object_list %}
                    <li>
                        {{ post.modify_date|date:'Y-m-d' }}&nbsp;
                        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                    </li>
                {% endfor %}
            </ul>
        </div>

    </div>
{% endblock content %}

{% block footer %}
    <div id="footer">&copy; Django for Python 2019.</div>
{% endblock %}

web/blog/templates/blog/post_archive_year.html
{% extends "base.html" %}
{% block title %}Post Archive{% endblock %}
{% block content %}
    <div id="content">
        <h1>Post Archive for {{ year|date:"Y" }}</h1>
        <ul>
            {% for date in date_list %}
                <li style="display:inline-block; margin-right:1em">
                    <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'m' %}">
                        {{ date|date:'F' }}
                    </a>
                </li>
            {% endfor %}
        </ul>

        <div>
            <ul>
                {% for post in object_list %}
                    <li>
                        {{ post.modify_date|date:'Y-m-d' }} &nbsp;
                        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                    </li>
                {% endfor %}
            </ul>
        </div>

    </div>
{% endblock content %}

{% block footer %}
    <div id="footer">&copy; Django for Python 2019.</div>
{% endblock %}

web/blog/templates/blog/post_change_list.html
{% extends "base.html" %}
{% block title %}Post Change List{% endblock %}
{% block content %}
    <div id="content">
        <h1>Post Change - {{ user }}</h1>

        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Owner</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for item in object_list %}
                <tr>
                    <td>{{ item.title }}</td>
                    <td>{{ item.description }}</td>
                    <td>{{ item.owner }}</td>
                    <td><a href="{% url 'blog:update' item.id %}">Update</a></td>
                    <td><a href="{% url 'blog:delete' item.id %}">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

{% block footer %}
    <div id="footer">&copy; Django for Python 2019.</div>
{% endblock %}

web/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% block title %}Post Confirm Delete{% endblock %}
{% block content %}
    <div id="content">
        <h1>Post Delete</h1>

        <form action="." method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"</p>
            <input type="submit" class="btn btn-primary" value="Confirm">
        </form>
    </div>
{% endblock content %}

{% block footer %}
    <div id="footer">&copy; Django for Python 2019.</div>
{% endblock %}

web/blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% block title %}Blog Detail{% endblock %}
{% block content %}
    <div id="content">
        <h2>{{ object.title }}</h2>
        <hr>
        <p class="other_posts" style="display:block; padding:0 1em 1em">
            {% if object.get_previous_by_modify_date %}
            <a href="{{ object.get_previous_post.get_absolute_url }}" title="View Previous Post" style="float:left;">
                &laquo;-- {{ object.get_previous_post }}
            </a>
            {% endif %}

            {% if object.get_next_by_modify_date %}
            <a href="{{ object.get_next_post.get_absolute_url }}" title="View Next Post" style="float:right">
                {{ object.get_next_post }} --&raquo;
            </a>
            {% endif %}
        </p>
        <hr style="clear:both; display:block">
        <p class="date">{{ object.modify_date|date:"j F Y" }}</p>
        <br>
        <div class="body">
            {{ object.content|linebreaks }}
        </div>

        <div>
            <strong>TAGS:</strong>
            {% load tagging_tags %}
            {% tags_for_object object as tags %}
            {% for tag in tags %}
            <a href="{% url 'blog:tagged_object_list' tag.name %}">{{ tag.name }}</a>
            {% endfor %}
            <a href="{% url 'blog:tag_cloud' %}"><i>[ TagCloud ]</i></a>
        </div>

        <br>
        <div>
            {% load disqus_tags %}
            {% disqus_show_comments %}
        </div>
    </div>
{% endblock %}

{% block footer %}
    <div id="footer">&copy; Django for Python 2019.</div>
{% endblock %}

web/blog/templates/blog/post_form.html
{% extends "base.html" %}
{% block title %}Post Form{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static 'css/form.css' %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Create/Update - {{ user }}</h1>

        <form action="." method="post">{% csrf_token %}

            {% if form.errors %}
            <p class="errornote">Wrong! Please correct the errors below.</p>
            {% endif %}

            <p>This is a creation or update form for your post.</p>

            <fieldset class="aligned">
                <div class="form-group">
                    {{ form.title.label_tag }} {{ form.title }}
                </div>
                <div class="form-group">
                    {{ form.slug.label_tag }} {{ form.slug }}
                </div>
                <div class="form-group">
                    {{ form.description.label_tag }} {{ form.description }}
                </div>
                <div class="form-group">
                    {{ form.content.label_tag }} {{ form.content }}
                </div>
                <div class="form-group">
                    {{ form.tag.label_tag }} {{ form.tag }}
                </div>
            </fieldset>

            <div class="submit-row">
                <input type="submit" class="btn btn-primary" value="Submit">
            </div>

            <script type="text/javascript">
                document.getElementById('id_title').focus();
            </script>
        </form>
    </div>
{% endblock content %}

{% block footer %}
    <div id="footer">&copy; Django for Python 2019.</div>
{% endblock %}

web/blog/templates/blog/post_search.html
{% extends "base.html" %}
{% block title %}Pos search.html {% endblock %}
{% block content %}
    <div id="content">
        <h1>Blog Search</h1>
        <!-- csrf_token 을 통해 크로스사이트 공격을 방어할 수 있음. -->
        <form action="." method="post">{% csrf_token %}
            {{ form.as_table }}
            <input type="submit" value="Submit">
        </form>
        <br><br>

        {% if object_list %}
            {% for post in object_list %}
                <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                <p>{{ post.description }}</p>
            {% endfor %}
        {% elif search_term %}
            <b><i>Search Word({{ search_term }}) is Not Found !</i></b>
        {% endif %}
    </div>
{% endblock %}